security:
    encoders:
        bcrypt:
            algorithm: bcrypt
            cost: 12

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }